### ISSUE TITLE
Basin Analysis Report - Data Units

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#16]
There are some users suggesting using both metric (SI) and imperial (US) units in the reports. This is still an undecided issue. The only decision we have now is to display the scale bar with both miles and km units (i.e., a dual-unit scale bar). See this page for an example: https://support.esri.com/en/technical-article/000011784

**Comment by lbross** [comment]
I implemented this for all the maps. There is a sample watershed report on AGOL for Elk_R_nr_Milner so you can take a look. It seems that there is a bug with the Pro API for the AlignToZeroPoint property that the tech article suggests. When I set it on the scale bar, the scale bar does not display. This isn't a problem for our scale bars because they both have a starting point of 0, but let me know if you think we should file a bug report with ESRI.
