### ISSUE TITLE
Basin Analysis Report - Precipitation Distribution Map

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#18]
Set precipitation intervals to integer numbers whenever possible. If that results to fewer intervals (<= 5), then change the interval to 0.5 inch.

**Comment by lbross** [comment]
What do you think about handling this the same way we handle the elevation interval? We calculate the interval list for 7 classes, the number of precipitation classes we settled on a few months ago. I can set the name field on the raster to be the rounded values for each of the classes. Example: 19.3-24.8 becomes 19-25. The lowest and highest classes would still have the decimal place because the data isn't perfect integers. The name field is used for the legend on the maps.

Is this also a problem for the Winter Precipitation map? That one will be harder because it uses continuous symbology.

**Comment by jdduh** [comment]
It should be the same as the elevation interval. The intervals on the same map are the same, it's not just rounding the interval values (which might create unequal intervals). Yes, the lower and upper class values would be the min and max of the precipitation data. Display them with 1 decimal place. Did we reclassify the winter precipitation data? If it's continuous symbology, then we don't have to set the class intervals.

**Comment by lbross** [comment]
Hmmm... with the elevation interval we use the actual values to do the classification so the rounding doesn't effect the classification. For example, one interval has a lower bound of 2438.4 and an upper bound of 2590.8. This is meters (because the DEM is meters) and we use these values for the reclassify. After the raster is done, we convert the values to feet and round so the name shows as 8000-8500. And this is what appears on the map legend. 

We could do the same think with PRISM. In my example above, we would use 19.3-24.8 in the reclassification but the legend would display 19-25. 

Alternatively, we could iterate through 1 inch intervals from larger to smaller (5, 4, 3, 2, 1, 0.5) until we get to 5 intervals and then use those values for BOTH the reclassification and the legend. Does that make sense?

We decided not to reclassify the Winter Precipitation data but we did set the number of classes to be the same as the Precip Distribution map so that the 2 maps would be comparable. The legend shows up to 8 decimal places by default and I don't know if that's a problem. I also don't know if there is a way to change it.

**Comment by lbross** [comment]
1. Calculate the precipitation range
2. Divide the range by 8 (this value is a parameter)
3. Round the output to the nearest integer to get the number of inches per interval. For example: If the range is 48.9, 48.9/8 = 6.11 so use a range of 6 inches
4. If the highest interval is < 1 inch, combine the highest and second highest intervals so no interval is too small
5. If the range is less than the value from step 2, calculate the intervals using 0.5 inches

**Comment by lbross** [comment]
I've never been 100% clear on the logic used to generate the interval lists. If you want to look at the C# implementation it's in the GeneralTools.CreateRangeArray() method. But it looks like it adjusts both the top and bottom values. What do we want to do if the lowest interval is < 1? Do we combine with 2nd lowest interval? Once I get the intervals into the array list, it's easy for me to adjust the values, so if you'd rather distribute it to another interval, let me know. Here is the "real world" example from Yampa.
![image](https://user-images.githubusercontent.com/11527966/130272231-9d76caa7-a432-4c67-bd91-896f50c1b8f6.png)

**Comment by lbross** [comment]
If upper or lower bound is less than 1, merge to adjacent range. If using 0.5 interval, if less than 0.5 merge to adjacent range.

**Comment by lbross** [comment]
This has been implemented in BAGIS Pro. New watershed reports for elk_r_nr_milner and Elwha have been uploaded to the portal
