### ISSUE TITLE
1991-2020 Prism and 2019 NLCD data

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#28]
The 1991-2020 Prism precipitation data is now available: http://webservices.geog.pdx.edu/arcgis/rest/services/BAGIS_PRISM_1991_2020

Also available are 1991-2020 tmin and tmax for July and August (for BAGIS-P), 2019 NLCD impervious (for BAGIS-P), and 2019 NLCD land cover.
http://webservices.geog.pdx.edu/arcgis/rest/services/BAGIS_Databin

We are still waiting for NWCC to provide a csv file containing the runoff data. Once we have the new data, we can use it to update the csv file posted on the NRCS GIS Hub. https://nwcc-nrcs.hub.arcgis.com/datasets/annual-runoff-averages. Together with the new PRISM data, this dataset allows the calculation of the annual runoff ratio (see #5).

The NLCD land cover is a new dataset for a new map in the watershed report. The color scheme of the land cover map is defined in the attribute table of the raster dataset. See a summary below.

Value,Red,Green,Blue,Opacity,NLCD_Land
0,0,0,0,0,Unclassified
11,70,107,159,255,Open Water
12,209,222,248,255,Perennial Snow/Ice
21,222,197,197,255,"Developed, Open Space"
22,217,146,130,255,"Developed, Low Intensity"
23,235,0,0,255,"Developed, Medium Intensity"
24,171,0,0,255,"Developed, High Intensity"
31,179,172,159,255,Barren Land
41,104,171,95,255,Deciduous Forest
42,28,95,44,255,Evergreen Forest
43,181,197,143,255,Mixed Forest
52,204,184,121,255,Shrub/Scrub
71,223,223,194,255,Herbaceous
81,220,217,57,255,Hay/Pasture
82,171,108,40,255,Cultivated Crops
90,184,217,235,255,Woody Wetlands
95,108,159,184,255,Emergent Herbaceous Wetlands

**Comment by jdduh** [comment]
![image](https://user-images.githubusercontent.com/11510708/145154979-e3865a31-9a12-4d37-85f0-3f79306aa08d.png)

**Comment by jdduh** [comment]
The abbreviations look good. Do we need to update the land cover imageservice? Or the labels are set by the codes?

**Comment by lbross** [comment]
I think the labels are stored in the .lyrx file so the service wouldn't need to change. I will try making the change and see if it helps.

**Comment by lbross** [comment]
Can you take a look at the 06228000_WY_USGS Watershed Report that I just posted to the portal? I was able to adjust the font sizes for the elevation zones and land cover maps. Please let me know if they look good or should be smaller. Note that the multi-panel maps are disabled in this report for debugging purposes.

**Comment by jdduh** [comment]
Have you also adjusted the legend item's patch height? You probably also need to make the patch height smaller. See this page for legend item properties. https://pro.arcgis.com/en/pro-app/2.7/help/layouts/work-with-legend-items.htm

**Comment by jdduh** [comment]
NWCC noticed several maps that have quite a bit of space between the map and the title and asked if it's possible to move the mapframe up slightly to avoid the legend overlap.

![image](https://user-images.githubusercontent.com/11510708/164582460-5ad8907e-f39b-43f5-a06c-b20c3b624470.png)

**Comment by lbross** [comment]
I will look into this, but I suspect this particular map may be one that didn't zoom correctly. You can check by loading the maps and then zooming to the AOI. I couldn't find this AOI on CS3

**Comment by jdduh** [comment]
I have put a copy of this AOI on CS3. It's C:\AOIs\Debug\10243260_NV_USGS_04132022.

**Comment by lbross** [comment]
I moved the Basin Analysis mapframe up 1.0 inches. Let's see how this looks with the various AOI geographies

**Comment by jdduh** [comment]
Missing color for NLCD herbaceous class (71) for an AOI in Utah. This is the latest 2.x addin (May 2023). Please note that the class name changed when including Alaska NLCD data (see #40). The nlcd_land_cover.lyrx seems to be the latest version.

![image](https://user-images.githubusercontent.com/11510708/236955800-5fec2063-8191-48eb-8be6-0bd9f28a2558.png)

![image](https://user-images.githubusercontent.com/11510708/236955878-df15da79-334f-44e7-a775-cd9dfa95c9a0.png)

![image](https://user-images.githubusercontent.com/11510708/236956059-51051ee4-3146-4440-9862-923d48a1e57e.png)

**Comment by lbross** [comment]
This problem is caused because the NLCD_Land attribute for class 71 is grassland/herbaceous in Alaska and herbaceous in North America. Alaska and North America share the same .lyrx file. It is also the same for both 2.x and 3.x. I just need to make sure that I always export it from 2.x because it is forwards but not backwards compatible.
If you look at the properties of the symbology that we are using, it is based on the NLCD_Land attribute rather than the value attribute. The quickest way to fix this would be to change the Alaska NLCD web service to set NLCD_Land for class 71 to herbaceous instead of grassland/herbaceous and update the .lyrx file accordingly. This would mean having to reclip all of the NLCD layers for Alaska to get the updated value. But we don't have as many Alaska AOIs as we have North American. This might be confusing because with Alaska we added class 72 which is Sedge/Herbaceous. I'm not sure if class 72 exists in North America?
The best long-term solution would be to change the .lyrx file so it keys off of Value rather than NLCD_Land. This would allow more flexibility in NLCD_Land values between the 2 webservices but the legend description may no longer be the same as the web service if the 2 services are different.
I have struggled to create an .lyrx file with all of the classes because the only way I found to do it is to find a basin with all classes which is nigh impossible. I'm not sure how you generated the updated Alaska .lyrx but if you could do this again, based on Value instead of NLCD_Land, that may be the best solution.

**Comment by jdduh** [comment]
Please rename the file extension name to .lyrx. This layer file uses value as the key. I have tested it on a lower-48 AOI. The map rendered correctly in BAGIS Pro interactive mode. Please verify that it works and use it to update the source on GitHub.

[nlcd_land_cover.txt](https://github.com/PSU-CSAR/bagis-pro/files/11436166/nlcd_land_cover.txt)

**Comment by lbross** [comment]
This is done. I did have some trouble with the NLCD layer on Alaska AOI's. The symptom was that 255 values showed up on the legend and Pro was trying to apply the legend as a Colormap. I reclipped the NLCD layer and it seemed to work correctly. Wanted to make a note of this in case you run into it on older Alaska AOIs.
