### ISSUE TITLE
Basin Analysis Report - Putting multiple maps on one page?

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#29]
There are several types of maps in the report that look the best when they are next to each other. NWCC is interested in testing out this cartographic design for the maps listed below. They acknowledge the possible impact on the aesthetics of the maps/layout. This technique hasn't been implemented in previous BAGIS releases.

AOI_Name + " Seasonal Precipitation Distribution"
- Winter (Nov-Mar) Precipitation Map
- Seasonal Precipitation Contribution: Dec, Jan, & Feb Map
- Seasonal Precipitation Contribution: Mar, Apr, & May Map
- Seasonal Precipitation Contribution: Jun, Jul, & Aug Map
- Seasonal Precipitation Contribution: Sep, Oct, & Nov Map

AOI_Name + " SNODAS SWE"
- SNODAS SWE Nov 1ST Map
- SNODAS SWE Dec 1ST Map
- SNODAS SWE Jan 1ST Map
- SNODAS SWE Feb 1ST Map
- SNODAS SWE Mar 1ST Map
- SNODAS SWE Apr 1ST Map
- SNODAS SWE May 1ST Map
- SNODAS SWE Jun 1ST Map
- SNODAS SWE Jul 1ST Map

AOI_Name + " SNODAS SWE"
- Average November SWE Delta Map
- Average December SWE Delta Map
- Average January SWE Delta Map
- Average February SWE Delta Map
- Average March SWE Delta Map
- Average April SWE Delta Map
- Average May SWE Delta Map
- Average Jun SWE Delta Map

**Comment by lbross** [comment]
I am attaching two mockups per your request for the 9 SWE maps. One with and one without sites. Please let me know if you would like any changes or variations prior to your meeting with NWCC on Wednesday.
[issue_29_no_sites.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8017963/issue_29_no_sites.pdf)
[issue_29.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8017964/issue_29.pdf)

**Comment by jdduh** [comment]
Thanks! These will work. The individual maps need to have their own subcaptions, i.e., months. Some map frames are overlapped, which makes the individual maps larger than they could be. The sites definitely are distractions on the map. I will let you know what NWCC prefers. 

- Geoffrey

**Comment by lbross** [comment]
The maps are in month order so you can infer the month based on the map title and the map's position. ie: the first is November and the last is July. I tried to make them as large as possible, but yes map frame could be smaller.

**Comment by jdduh** [comment]
NWCC likes the design. Here are their comments.
1. Remove site numbers but keep the symbols on the map (consider using smaller site symbols)
2. Label the individual maps (e.g., Nov 1, Dec 1 etc.) for the SWE map, change map title to "SNODAS Mean SWE"
3. Label the individual maps (e.g., Dec, Jan, & Feb, etc.) for the Seasonal Precipitation Contribution, also update the map title.
4. Label the individual maps (e.g., Nov, Dec, etc.) for the SNODAS Mean SWE Delta, also update the map title.

**Comment by lbross** [comment]
I am going to look into saving/loading layouts from a file rather than building these all in the code. It might be easier to manage. A few questions/comments:
1. You mentioned that some of the map frames overlapped. Should I take a closer look at these and make the maps smaller?
2. The Seasonal Precipitation map series is only 4 maps. Should this be in a different layout? 4 maps can be bigger than 8-9 maps on a page.
3. I will send some samples of different symbol sizes to see what looks best
4. In the ArcGIS Pro client, we currently treat these maps individually with the same process as viewing all the other maps. This means 9 buttons for SWE maps, 8 buttons for SWE Delta maps, etc. Do you want me to strip out this functionality? Or add new buttons for the map series pages?

**Comment by jdduh** [comment]
1. How did you create the mockup? You should be able to see the map frame outlines (see here for an example).
![image](https://user-images.githubusercontent.com/11510708/154182388-b70872c0-2a50-4a54-8834-ed151ef56804.png)

This is why I think some map frames are overlapped.
![image](https://user-images.githubusercontent.com/11510708/154182751-9c930910-1a0e-413f-99aa-12af71675b0f.png)

2. Use a different layout for the one with only 4 maps.
3. Thanks!
4. If the multiple map frame design works well, then we can switch to using just one map layout (i.e., one menu button) to display the maps.

**Comment by lbross** [comment]
Here is another sample for you to look at. The sites are at 9 pt. The map outlines should be close, but not overlapping now. 
I think the individual map titles could be a little smaller. The export looks slightly different than the display in ArcGIS Pro. I am using Pro to create the layouts manually. I'm hoping to save the layout file and update the contents programmatically for each AOI.
[issue_29_v1.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8082925/issue_29_v1.pdf)

**Comment by jdduh** [comment]
I would use an even smaller symbol size for the SNOTEL and Snow Course site (6 maybe?). The layout looks good. If you need more vertical space, then you can make the legend smaller. I agree that the individual map titles could be smaller.

**Comment by lbross** [comment]
Here's another sample with the changes you requested. I don't think the map squares can be any bigger with the titles in between
[issue_29_v2.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8083605/issue_29_v2.pdf)

**Comment by jdduh** [comment]
Looks good!

**Comment by lbross** [comment]
Attaching the SWE Delta map for your review. Please let me know if you have any suggestions.
[SNODAS Delta Layout.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8210607/SNODAS.Delta.Layout.pdf)

**Comment by jdduh** [comment]
Looks good. The layout also works well with 8 maps. The legend has an extra text "NAME." I'm not sure where it comes from. Please make sure that the legend won't obscure the May SWE delta map.

**Comment by lbross** [comment]
The extra "NAME" text is a bug. I will fix. Here is a sample of the 4 panel map.
[
[SNODAS Precipitation Contribution.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8294153/SNODAS.Precipitation.Contribution.pdf)
]

**Comment by jdduh** [comment]
This looks great. I notice that you draw the outlines of the mapframes in this document. It doesn't look bad, but we should be consistent with the design of the other two multiple-map pages.

**Comment by lbross** [comment]
Good catch! I had them turned on when I was placing the mapframes. I will turn them off. Easy to do.

**Comment by jdduh** [comment]
This is a bug for some AOIs, but not all. The legend doesn't render all value classes.

![image](https://user-images.githubusercontent.com/11510708/208172812-d275516d-8b8c-4ccd-9134-31b12069f0d9.png)

**Comment by jdduh** [comment]
The SALT R NR ROSSEVELT AOI is the only AOI having this issue so far. I have put a copy of the AOI at ftp://basins.geog.pdx.edu/BAGIS/BAGIS_aois/. The zipped file size of the AOI is 1.3GB.

**Comment by lbross** [comment]
I'm not going to be able to look at this issue until next week. There's a chance it might be fixed with some unrelated changes that I've already made, but I'm not optimistic. I'm hoping to post a new version at lunchtime with most of the fixes, but that will be it until next week.

**Comment by jdduh** [comment]
Still has the same issue with the latest addin. All the pagx were removed before the rerun. The legend is set to the July 1 layer. The raster layer has only a single pixel value - zero for the basin.

![image](https://user-images.githubusercontent.com/11510708/208532149-17eb3158-ad37-4e84-8972-1b8d311f5ee6.png)

**Comment by lbross** [comment]
Yes. I was able to recreate the error yesterday. I'm not sure how I will resolve it, but am working on it.

**Comment by lbross** [comment]
This problem is due to needing one of the maps in the series to have values in each of the class breaks so that the legend can be rendered correctly. The tools in Pro for manipulating the legend are extremely limited so it has to be based on a map in a mapframe that it can be linked to. I've figured out how to determine if a map has all of the class breaks but this doesn't solve the problem if there isn't a map with all the class breaks. The only thing I can think of is creating a "dummy" map and map frame where I create pixels in each of the class breaks and pointing the legend at that. I can make it really small or hide it behind one of the real maps so you will never see it.
Do you know of a gp tool that can create a raster based on an array of values or can you think of a way to manipulate one of the "real" SWE rasters to meet this requirement?

**Comment by jdduh** [comment]
Create Random Raster tool can achieve what you described. I'm not sure if the output raster's georeference and dimension parameters have to match the SNODAS data when you generating the layout.

**Comment by lbross** [comment]
I'm working on a proof of concept on this. The Create Random Raster tool is getting me close. Do you know if there is any way to force it to give me a cell with a 0 value? I tried the uniform distribution option with 0 as the minimum and 652.0 as the maximum. I use one of the SWE layers to set the extent and I set the cell size to be the same as SWE. I would do some trial and error myself but it seems that there is a sense of urgency on this request. If the POC works, we are probably still a few days out from having it working for all 3 of these maps. Let me know if you want the Excel test earlier than that.

**Comment by jdduh** [comment]
There are the two remaining bugs of the batch tool (at least for the AOIs that we tested on). I suspect that by forcing the splitting of the Slope Distribution text would get us around the pdf conversion/rendering bug and fix the problem.
If you can reduce the size of the dummy raster, then you might be able to speed up the processing time. If the dummy raster is required to have the same extend as the SNODAS rasters, then you can use a coarse resolution. You might also need to define the projection for the random raster. I cannot think of a better way to force zero in a raster other than using the CON tool to set a range of pixel value to zero (e.g., CON (dummyraster < MEAN_OF_THE_DUMMYRASTER, 0, dummyraster).

**Comment by jdduh** [comment]
Just so you know that I got the same "elev ation" problem on a different computer. The computer is a "standard" PSU OIT built. I suspect the bug can be reproduced on most computers.

**Comment by jdduh** [comment]
Question: "This problem is due to needing one of the maps in the series to have values in each of the class breaks so that the legend can be rendered correctly. "
Does this mean that the previously generated reports all have wrong legends? July probably is the driest month for the AOIs in the western US. Will setting the legend to the wetter month (e.g., January) resolve the issue?

**Comment by lbross** [comment]
The existing code tried to pick the mapframe that contained a map with all of the class breaks. In this example, none of them had all the class breaks so it took July which is the map frame the legend is tied to in the layout. So the previously generated reports could be "wrong" if none of the maps had all of the class breaks. The colors aren't wrong, but the legend could be missing a class break.

**Comment by jdduh** [comment]
Can the dummy raster with only two values (min and max of SNODAS SWE) correctly create the legend? If yes, then we can use the Create Random Raster and Reclass tool to guarantee the output raster having the min and max SNODAS values.

**Comment by lbross** [comment]
I think it has to have values in each of the 5 Class Breaks. I am taking a step back this afternoon to see if I can do something different when creating the ClassifyColorizerDefinition that will fix this. Back when I first created this, there was little documentation on Raster symbology, but maybe there is more now?

**Comment by lbross** [comment]
What if we reclassified the rasters so that the values are discrete? Then we could use a uniquevalue renderer which I think might be easier?

**Comment by jdduh** [comment]
Reclassifying the rasters would add additional computation time and data space to the process. I tested the "Apply Symbology From Layer" tool. The data range of the Input Layer (i.e., a raster) doesn't affect the appearance of the Symbology Layer. It seems that the 0 in the July 1st SNODAS SWE layer shouldn't alter the symbology in the legend. Similarly, if the Symbology rendered is set up correctly, then the appearance of the symbology has nothing to do with raster cell values. 

Here is an image that I applied the June symbology layer on the July SNODAS SWE layer for the Salt R. Nr Roosevelt basin.

![image](https://user-images.githubusercontent.com/11510708/209222023-c398f3e5-878d-42f2-9f0f-55d807e80db2.png)

**Comment by jdduh** [comment]
Another possible solution is to use the Jan 1st layer as the legend. January 1st SNOAS SWE layer has the least mount of 0 pixels among the SNODAS SWE layers.

**Comment by lbross** [comment]
I can test the "Apply Symbology From Layer" tool but I'm skeptical that it will work across AOI's. The class breaks are different for each AOI depending on the data. It works with the classified, discrete raster approach because if we use the value as the key, the values are always 1 .. 7.

Jan 1st is better than June because it probably has data in more of the class breaks, but if it doesn't have data in ALL of the class breaks, some will drop out.

Reclassifying the rasters does add time, but it wouldn't be that much more space because the continuous rasters for the delta and seasonal precipitation data sets could be deleted once we have the classified rasters.

**Comment by jdduh** [comment]
Thanks for the additional information. I am fine with the reclassifying approach. 
Speaking of keeping the analysis data, we need to create a document listing the files created by the basin analysis report tool so that users can use them directly in ArcGIS. I will start a Google doc/Google site page for this purpose.

**Comment by lbross** [comment]
Just to support my argument about why using a template across AOI's won't work with continuous data classification approach. I create the template using the Imnaha AOI because it had a month will all the class breaks. I then ran Marlette and exported the results without a template. I then applied the Imnaha template to Marlette. You can see that the classifications change incorrectly because the class breaks are in different places.
On a related note, I am working through the reclassifying approach using the Seasonal Precipitation map because there are only 4 maps. It's looking good but I think I may have found a bug in my code to create the class breaks :-( I'll send an update when I've fixed that and have the POC working. 
For all AOI's I'm going to add the code to reclassify when the layers are created so the batch process will need to be re-run for all of them :-(
[snodas_imnaha.pdf](https://github.com/PSU-CSAR/bagis-pro/files/10290905/snodas_imnaha.pdf)
[snodas_marlette_no_template.pdf](https://github.com/PSU-CSAR/bagis-pro/files/10290906/snodas_marlette_no_template.pdf)
[snodas_marlette_with_template.pdf](https://github.com/PSU-CSAR/bagis-pro/files/10290907/snodas_marlette_with_template.pdf)

No problem to work on the documentation next year :-)

**Comment by lbross** [comment]
I'm running some final tests now, but hope to post an updated add-in on basins shortly. Once I finally got the methodology working for the quarterly precipitation maps, the other two fell in quickly. Note that the classified layers are created at the same time as their source layers are created so you will need to rerun the batch tool to get the new layers created for the maps. There was a bug on the quarterly precipitation class breaks. That is also fixed.

**Comment by lbross** [comment]
I just posted a new add-in to basins. The errors with the maps that I saw yesterday were due to a corrupted project in ArcGIS Pro. When using this project, the geoprocessor failed to apply the layer file to the Land Ownership map and the symbology was not applied correctly to the Precipitation Contribution map even though the 2 maps are completely unrelated. Running the add-in in a new project fixed both these problems. After 1.5 hours of troubleshooting :-( Please download it and let me know if you find other issues. And Happy New Year!!

**Comment by jdduh** [comment]
I got the new addin and will report back when the batch of reports are generated. Thanks!
